### ISSUE TITLE
Sandboxed Compiles stopped working

### ISSUE THREAD

**Issue by Shadowxp13** [yu-i-i/overleaf-cep#84]
## Steps to Reproduce
I am currently using an image whose source is this repo's upstream, patched up to version 5.5.5 according to the steps done in discussion [#78](https://github.com/yu-i-i/overleaf-cep/discussions/78), alongside MongoDB 8.0 and Redis 7.4.

That being said, trying to compile any project promptly returns "Server Error: Sorry, something went wrong and your project could not be compiled. Please try again in a few moments."

## Expected Behaviour
The compile should've sucessfully completed, but it did not. I've tried disabling sandboxed compiles as a test and everything works as expected.

## Observed Behaviour
Here is the `clsi.log` output:

```
Initializing metrics
Set UV_THREADPOOL_SIZE=16
Using default settings from /overleaf/services/clsi/config/settings.defaults.js
Using settings from /etc/overleaf/settings.js
{"name":"default","hostname":"d2986b9edff6","pid":195,"level":20,"commandRunnerPath":"./DockerRunner","msg":"selecting command runner for clsi","time":"2025-11-06T17:32:57.306Z","v":0}
{"name":"default","hostname":"d2986b9edff6","pid":195,"level":20,"msg":"using docker runner undefined","time":"2025-11-06T17:32:57.830Z","v":0}
{"name":"default","hostname":"d2986b9edff6","pid":195,"level":20,"maxAge":3600000,"msg":"starting container expiry","time":"2025-11-06T17:32:57.830Z","v":0}
{"name":"default","hostname":"d2986b9edff6","pid":195,"level":20,"EXPIRY_TIMEOUT":86400000,"msg":"project assets kept timeout","time":"2025-11-06T17:32:57.886Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":30,"target":"2025-11-08T16:25:22.735Z","msg":"Lifespan limited","time":"2025-11-06T17:32:58.753Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":20,"msg":"CLSI starting up, listening on 127.0.0.1:3013 undefined","time":"2025-11-06T17:32:58.780Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":20,"msg":"Load tcp agent listening on load port 3048 undefined","time":"2025-11-06T17:32:58.780Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":20,"msg":"Load http agent listening on load port 3049 undefined","time":"2025-11-06T17:32:58.780Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":20,"projectId":"690565472504143289c303c9","userId":"66de98c535b4358e1dafac09","msg":"syncing resources to disk","time":"2025-11-06T17:33:15.483Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":20,"projectId":"690565472504143289c303c9","userId":"66de98c535b4358e1dafac09","msg":"full sync","time":"2025-11-06T17:33:15.484Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":20,"state":"ac31ed88fddf0b77a2891d06d3afa407150ab3c8","basePath":"/var/lib/overleaf/data/compiles/690565472504143289c303c9-66de98c535b4358e1dafac09","msg":"writing sync state","time":"2025-11-06T17:33:15.619Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":20,"projectId":"690565472504143289c303c9","userId":"66de98c535b4358e1dafac09","timeTaken":137,"msg":"written files to disk","time":"2025-11-06T17:33:15.620Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":20,"compileDir":"/var/lib/overleaf/data/compiles/690565472504143289c303c9-66de98c535b4358e1dafac09","mainFile":"00 - Corpo LaTeX/Corpo Duas Colunas.tex","usesTikzExternalize":false,"usesPsTool":false,"msg":"checked for packages needing main file as output.tex","time":"2025-11-06T17:33:15.621Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":20,"directory":"/var/lib/overleaf/data/compiles/690565472504143289c303c9-66de98c535b4358e1dafac09","compiler":"pdflatex","timeout":180000,"mainFile":"00 - Corpo LaTeX/Corpo Duas Colunas.tex","environment":{"OVERLEAF_PROJECT_ID":"690565472504143289c303c9","CHKTEX_OPTIONS":"-nall -e9 -e10 -w15 -w16","CHKTEX_ULIMIT_OPTIONS":"-t 5 -v 64000"},"flags":["-shell-escape","-file-line-error","-recorder"],"stopOnFirstError":false,"msg":"starting compile","time":"2025-11-06T17:33:15.621Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":20,"projectId":"690565472504143289c303c9-66de98c535b4358e1dafac09","msg":"running docker container","time":"2025-11-06T17:33:15.622Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":20,"containerName":"project-690565472504143289c303c9-66de98c535b4358e1dafac09-0e7fdd34a1dd9cf2a2527da939178934","msg":"starting container","time":"2025-11-06T17:33:15.623Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":20,"containerId":"project-690565472504143289c303c9-66de98c535b4358e1dafac09-0e7fdd34a1dd9cf2a2527da939178934","msg":"attached to container","time":"2025-11-06T17:33:15.633Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":20,"err":{"message":"(HTTP code 500) server error - cannot start a stopped process: unknown ","name":"Error","stack":"Error: (HTTP code 500) server error - cannot start a stopped process: unknown \n    at /overleaf/node_modules/docker-modem/lib/modem.js:383:17\n    at getCause (/overleaf/node_modules/docker-modem/lib/modem.js:418:7)\n    at Modem.buildPayload (/overleaf/node_modules/docker-modem/lib/modem.js:379:5)\n    at IncomingMessage.<anonymous> (/overleaf/node_modules/docker-modem/lib/modem.js:347:16)\n    at IncomingMessage.emit (node:events:531:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","info":{}},"projectId":"690565472504143289c303c9-66de98c535b4358e1dafac09","msg":"error running container so destroying and retrying","time":"2025-11-06T17:33:15.768Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":20,"containerId":"project-690565472504143289c303c9-66de98c535b4358e1dafac09-0e7fdd34a1dd9cf2a2527da939178934","msg":"destroying docker container","time":"2025-11-06T17:33:15.768Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":20,"containerId":"project-690565472504143289c303c9-66de98c535b4358e1dafac09-0e7fdd34a1dd9cf2a2527da939178934","msg":"destroyed container","time":"2025-11-06T17:33:15.779Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":20,"containerName":"project-690565472504143289c303c9-66de98c535b4358e1dafac09-0e7fdd34a1dd9cf2a2527da939178934","msg":"starting container","time":"2025-11-06T17:33:15.779Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":20,"containerId":"project-690565472504143289c303c9-66de98c535b4358e1dafac09-0e7fdd34a1dd9cf2a2527da939178934","msg":"attached to container","time":"2025-11-06T17:33:15.827Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":50,"err":{"message":"(HTTP code 500) server error - cannot start a stopped process: unknown ","name":"Error","stack":"Error: (HTTP code 500) server error - cannot start a stopped process: unknown \n    at /overleaf/node_modules/docker-modem/lib/modem.js:383:17\n    at getCause (/overleaf/node_modules/docker-modem/lib/modem.js:418:7)\n    at Modem.buildPayload (/overleaf/node_modules/docker-modem/lib/modem.js:379:5)\n    at IncomingMessage.<anonymous> (/overleaf/node_modules/docker-modem/lib/modem.js:347:16)\n    at IncomingMessage.emit (node:events:531:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","info":{}},"projectId":"690565472504143289c303c9","msg":"error running compile","time":"2025-11-06T17:33:15.944Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":20,"responseTimeMs":474,"req":{"method":"POST","url":"/project/690565472504143289c303c9/user/66de98c535b4358e1dafac09/compile?compileBackendClass=n2d&compileGroup=standard","remoteAddress":"127.0.0.1","headers":{"user-agent":"node-fetch/1.0 (+https://github.com/bitinn/node-fetch)","content-length":"66382"},"projectId":"690565472504143289c303c9","userId":"66de98c535b4358e1dafac09"},"res":{"statusCode":500,"headers":{"content-length":"933"}},"msg":"POST /project/690565472504143289c303c9/user/66de98c535b4358e1dafac09/compile?compileBackendClass=n2d&compileGroup=standard","time":"2025-11-06T17:33:15.947Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":20,"cache":"/var/lib/overleaf/data/output/690565472504143289c303c9-66de98c535b4358e1dafac09/generated-files","dir":"19a5a2e56d8-356b04a2ff3661cb","msg":"removed expired cache dir","time":"2025-11-06T17:33:15.949Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":20,"rss":"84.37","heapTotal":"25.35","heapUsed":"22.79","external":"18.58","arrayBuffers":"0.06","msg":"process.memoryUsage()","time":"2025-11-06T17:33:58.603Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":20,"rss":"84.87","heapTotal":"25.35","heapUsed":"23.28","external":"18.58","arrayBuffers":"0.06","msg":"process.memoryUsage()","time":"2025-11-06T17:34:58.603Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":20,"rss":"85.12","heapTotal":"26.35","heapUsed":"23.05","external":"18.58","arrayBuffers":"0.06","msg":"process.memoryUsage()","time":"2025-11-06T17:35:58.603Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":20,"rss":"85.12","heapTotal":"26.35","heapUsed":"23.51","external":"18.58","arrayBuffers":"0.06","msg":"process.memoryUsage()","time":"2025-11-06T17:36:58.603Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":20,"rss":"85.12","heapTotal":"25.35","heapUsed":"23.24","external":"18.58","arrayBuffers":"0.06","msg":"process.memoryUsage()","time":"2025-11-06T17:37:58.602Z","v":0}
{"name":"clsi","hostname":"d2986b9edff6","pid":195,"level":20,"rss":"85.12","heapTotal":"25.35","heapUsed":"22.94","external":"18.58","arrayBuffers":"0.06","msg":"process.memoryUsage()","time":"2025-11-06T17:38:58.603Z","v":0}
```

And here is a snippet of my `variables.env` and my `overleaf.rc` files

```
########################
## Sandboxed Compiles ##
########################

TEX_LIVE_DOCKER_IMAGE=texlive/texlive:latest-full
ALL_TEX_LIVE_DOCKER_IMAGES=texlive/texlive:latest-full, zydou/texlive:2022-xenial
ALL_TEX_LIVE_DOCKER_IMAGE_NAMES=TeXLive-Latest, TeXLive-2022
TEX_COMPILER_EXTRA_FLAGS=-shell-escape -file-line-error -recorder

OPTIMISE_PDF=true
```

```
#### Overleaf RC ####

PROJECT_NAME=overleaf

# Sharelatex container
# Uncomment the OVERLEAF_IMAGE_NAME variable to use a user-defined image.
# OVERLEAF_IMAGE_NAME=sharelatex/sharelatex
OVERLEAF_DATA_PATH=data/overleaf
OVERLEAF_LOG_PATH=logs/overleaf
SERVER_PRO=true
OVERLEAF_LISTEN_IP=127.0.0.1
OVERLEAF_PORT=63423

# Sibling Containers
SIBLING_CONTAINERS_ENABLED=true
DOCKER_SOCKET_PATH=/var/run/docker.sock

# Mongo configuration
MONGO_ENABLED=true
MONGO_DATA_PATH=data/mongo
MONGO_IMAGE=mongo
MONGO_VERSION=8.0


# Redis configuration
REDIS_ENABLED=true
REDIS_DATA_PATH=data/redis
REDIS_IMAGE=redis:7.4
REDIS_AOF_PERSISTENCE=true
```

## Context
According to the official 6.0.0 release notes, and [this](https://docs.overleaf.com/on-premises/maintenance/updating-mongodb) page, I've updated MongoDB to version 8.0 and Redis to 7.4 as a preparation step for the new release yesterday, since version 5.5.0 already supports that and everything worked smoothly, including sandboxed compiles, until today. Therefore, I don't think that this is the root of my issue. Thank you for your work!

**Comment by zestreito** [comment]
I ran into this same issue after upgrading docker packages from `5:28.5.1-1~debian.13~trixie` to `5:28.5.2-1~debian.13~trixie` yesterday

Rolling them back to `5:28.5.1-1` fixed it for me.

**Comment by yu-i-i** [comment]
I'm still on Ubuntu 22.04 with an old docker. I'll update it on Sunday and try to find out what's going on.

**Comment by simon4477** [comment]
> > I ran into this same issue after upgrading docker packages from `5:28.5.1-1~debian.13~trixie` to `5:28.5.2-1~debian.13~trixie` yesterday
> > Rolling them back to `5:28.5.1-1` fixed it for me.
> 
> I was about to write that rolling back from version `5:28.5.2-1~ubuntu.24.04~noble` to `5:28.4.0-1~ubuntu.24.04~noble` fixed it for me. Version `5:28.5.1-1~ubuntu.24.04~noble`, however, did not work for me.

@Shadowxp13
I am having the same issue on ubuntu 24.04, i rolled back to `5:28.4.0-1~ubuntu.24.04~noble` (`Docker version 28.4.0, build d8eb465`) but it didn't work for me. I also downgraded to `5:27.x` but it still didn't work. could you please provide the steps how you fixed the issue?

**Comment by Shadowxp13** [comment]
Hi @simon4477 and @squizz617 !

My exact steps were actually checking the apt history logs using ` grep "upgrade " /var/log/apt/history.log` so I could tell exactly which packages were updated, and its output is something like this (I've ran this on WSL, that's why the ubuntu version is different from what is described on my original issue):

```
Upgrade: containerd.io:amd64 (1.7.28-0~ubuntu.22.04~jammy, 1.7.29-1~ubuntu.22.04~jammy), docker-compose-plugin:amd64 (2.39.4-0~ubuntu.22.04~jammy, 2.40.3-1~ubuntu.22.04~jammy), docker-ce-cli:amd64 (5:28.4.0-1~ubuntu.22.04~jammy, 5:28.5.2-1~ubuntu.22.04~jammy), docker-buildx-plugin:amd64 (0.28.0-0~ubuntu.22.04~jammy, 0.29.1-1~ubuntu.22.04~jammy), docker-ce:amd64 (5:28.4.0-1~ubuntu.22.04~jammy, 5:28.5.2-1~ubuntu.22.04~jammy), cloud-init:amd64 (25.1.4-0ubuntu0~22.04.1, 25.2-0ubuntu1~22.04.1), docker-ce-rootless-extras:amd64 (5:28.4.0-1~ubuntu.22.04~jammy, 5:28.5.2-1~ubuntu.22.04~jammy), snapd:amd64 (2.68.5+ubuntu22.04.1, 2.71+ubuntu22.04), distro-info-data:amd64 (0.52ubuntu0.9, 0.52ubuntu0.11)
End-Date: 2025-11-07  00:00:55
```

After this, I've downgraded every package on this list that was related to docker to the previous version present on the output of the previous command, by using `sudo apt-get install containerd.io=1.7.28-0~ubuntu.24.04~noble docker-compose-plugin=2.39.4-0~ubuntu.24.04~noble docker-ce=5:28.4.0-1~ubuntu.24.04~noble docker-ce-cli=5:28.4.0-1~ubuntu.24.04~noble docker-ce-rootless-extras=5:28.4.0-1~ubuntu.24.04~noble  docker-buildx-plugin=0.28.0-0~ubuntu.24.04~noble`. 

As an additional step to prevent those packages from auto-uograding for now, I've set them on hold using `sudo apt-mark hold containerd.io docker-compose-plugin docker-ce docker-ce-cli docker-ce-rootless-extras docker-buildx-plugin`.

That's all! Best of luck for you!

**Comment by simon4477** [comment]
> Hi [@simon4477](https://github.com/simon4477) and [@squizz617](https://github.com/squizz617) !
> 
> My exact steps were actually checking the apt history logs using ` grep "upgrade " /var/log/apt/history.log` so I could tell exactly which packages were updated, and its output is something like this (I've ran this on WSL, that's why the ubuntu version is different from what is described on my original issue):
> 
> ```
> Upgrade: containerd.io:amd64 (1.7.28-0~ubuntu.22.04~jammy, 1.7.29-1~ubuntu.22.04~jammy), docker-compose-plugin:amd64 (2.39.4-0~ubuntu.22.04~jammy, 2.40.3-1~ubuntu.22.04~jammy), docker-ce-cli:amd64 (5:28.4.0-1~ubuntu.22.04~jammy, 5:28.5.2-1~ubuntu.22.04~jammy), docker-buildx-plugin:amd64 (0.28.0-0~ubuntu.22.04~jammy, 0.29.1-1~ubuntu.22.04~jammy), docker-ce:amd64 (5:28.4.0-1~ubuntu.22.04~jammy, 5:28.5.2-1~ubuntu.22.04~jammy), cloud-init:amd64 (25.1.4-0ubuntu0~22.04.1, 25.2-0ubuntu1~22.04.1), docker-ce-rootless-extras:amd64 (5:28.4.0-1~ubuntu.22.04~jammy, 5:28.5.2-1~ubuntu.22.04~jammy), snapd:amd64 (2.68.5+ubuntu22.04.1, 2.71+ubuntu22.04), distro-info-data:amd64 (0.52ubuntu0.9, 0.52ubuntu0.11)
> End-Date: 2025-11-07  00:00:55
> ```
> 
> After this, I've downgraded every package on this list that was related to docker to the previous version present on the output of the previous command, by using `sudo apt-get install containerd.io=1.7.28-0~ubuntu.24.04~noble docker-compose-plugin=2.39.4-0~ubuntu.24.04~noble docker-ce=5:28.4.0-1~ubuntu.24.04~noble docker-ce-cli=5:28.4.0-1~ubuntu.24.04~noble docker-ce-rootless-extras=5:28.4.0-1~ubuntu.24.04~noble docker-buildx-plugin=0.28.0-0~ubuntu.24.04~noble`.
> 
> As an additional step to prevent those packages from auto-uograding for now, I've set them on hold using `sudo apt-mark hold containerd.io docker-compose-plugin docker-ce docker-ce-cli docker-ce-rootless-extras docker-buildx-plugin`.
> 
> That's all! Best of luck for you!

@Shadowxp13

### 🫡
Thank you, your assistance is highly appreciated🫡

Worked like a charm 🙂

**Comment by simon4477** [comment]
@yu-i-i Would the new image be v6 (including the `clsi-profile.json` fix)?

**Comment by ThexXTURBOXx** [comment]
When migrating my Overleaf instance to a new server, I noticed an additional issue (which is fixed in the current main branch).
My old server ran Docker version 27.2.0, build 3ab4256 whilst my new server is already at Docker version 29.0.0, build 3d4129b and something changed in the meantime such that this change is actually necessary (also in the v5 images):
https://github.com/yu-i-i/overleaf-cep/commit/f09a494e5606a57a83f4f6559c13d52939b8a3de
Thus, in order to fix compiles not working on my new server, I had to do the following:
1. Start Overleaf using `bin/start`
2. Wait for it to have started
3. Run `bin/shell`
4. Apply the change (i.e., https://github.com/yu-i-i/overleaf-cep/commit/f09a494e5606a57a83f4f6559c13d52939b8a3de) in the file `/overleaf/services/clsi/app/js/DockerRunner.js` (for this, I installed `nano` inside the container using `apt` commands - there may be some preinstalled tool, which also works, though!)
5. Exit out of the container shell using <kbd>Ctrl</kbd>+<kbd>D</kbd>
6. Run `bin/stop`
7. Wait for it to stop
8. Run `bin/start`
9. Now, everything should work!

**Comment by yu-i-i** [comment]
@ThexXTURBOXx Thanks for that. I’ll wait until they publish a new version, and then I’ll update the images.

**Comment by moschlar** [comment]
@yu-i-i This has been fixed since `ext-v3.2`, hasn't it?

**Comment by yu-i-i** [comment]
> [@yu-i-i](https://github.com/yu-i-i) This has been fixed since `ext-v3.2`, hasn't it?

https://github.com/yu-i-i/overleaf-cep/issues/84#issuecomment-3532829964 is not fixed yet.
